# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from gym.common.protobuf import gym_pb2 as gym__pb2


class PlayerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Greet = channel.unary_unary(
        '/Player/Greet',
        request_serializer=gym__pb2.Info.SerializeToString,
        response_deserializer=gym__pb2.Info.FromString,
        )
    self.CallLayout = channel.unary_unary(
        '/Player/CallLayout',
        request_serializer=gym__pb2.Layout.SerializeToString,
        response_deserializer=gym__pb2.Result.FromString,
        )


class PlayerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Greet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallLayout(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PlayerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Greet': grpc.unary_unary_rpc_method_handler(
          servicer.Greet,
          request_deserializer=gym__pb2.Info.FromString,
          response_serializer=gym__pb2.Info.SerializeToString,
      ),
      'CallLayout': grpc.unary_unary_rpc_method_handler(
          servicer.CallLayout,
          request_deserializer=gym__pb2.Layout.FromString,
          response_serializer=gym__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Player', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class ManagerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Greet = channel.unary_unary(
        '/Manager/Greet',
        request_serializer=gym__pb2.Info.SerializeToString,
        response_deserializer=gym__pb2.Info.FromString,
        )
    self.CallTask = channel.unary_unary(
        '/Manager/CallTask',
        request_serializer=gym__pb2.Task.SerializeToString,
        response_deserializer=gym__pb2.Report.FromString,
        )


class ManagerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Greet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ManagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Greet': grpc.unary_unary_rpc_method_handler(
          servicer.Greet,
          request_deserializer=gym__pb2.Info.FromString,
          response_serializer=gym__pb2.Info.SerializeToString,
      ),
      'CallTask': grpc.unary_unary_rpc_method_handler(
          servicer.CallTask,
          request_deserializer=gym__pb2.Task.FromString,
          response_serializer=gym__pb2.Report.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Manager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class AgentStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Greet = channel.unary_unary(
        '/Agent/Greet',
        request_serializer=gym__pb2.Info.SerializeToString,
        response_deserializer=gym__pb2.Info.FromString,
        )
    self.CallInstruction = channel.unary_unary(
        '/Agent/CallInstruction',
        request_serializer=gym__pb2.Instruction.SerializeToString,
        response_deserializer=gym__pb2.Evaluation.FromString,
        )


class AgentServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Greet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallInstruction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AgentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Greet': grpc.unary_unary_rpc_method_handler(
          servicer.Greet,
          request_deserializer=gym__pb2.Info.FromString,
          response_serializer=gym__pb2.Info.SerializeToString,
      ),
      'CallInstruction': grpc.unary_unary_rpc_method_handler(
          servicer.CallInstruction,
          request_deserializer=gym__pb2.Instruction.FromString,
          response_serializer=gym__pb2.Evaluation.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Agent', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class MonitorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Greet = channel.unary_unary(
        '/Monitor/Greet',
        request_serializer=gym__pb2.Info.SerializeToString,
        response_deserializer=gym__pb2.Info.FromString,
        )
    self.CallInstruction = channel.unary_unary(
        '/Monitor/CallInstruction',
        request_serializer=gym__pb2.Instruction.SerializeToString,
        response_deserializer=gym__pb2.Evaluation.FromString,
        )


class MonitorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Greet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CallInstruction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MonitorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Greet': grpc.unary_unary_rpc_method_handler(
          servicer.Greet,
          request_deserializer=gym__pb2.Info.FromString,
          response_serializer=gym__pb2.Info.SerializeToString,
      ),
      'CallInstruction': grpc.unary_unary_rpc_method_handler(
          servicer.CallInstruction,
          request_deserializer=gym__pb2.Instruction.FromString,
          response_serializer=gym__pb2.Evaluation.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Monitor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
