#!/usr/bin/env python3.7
# coding=utf-8

import sys

from gym.common.app import App
from gym.player.player import Player


class GymPlayer(App):
    def __init__(self):
        App.__init__(self,
            app_cls = Player,
            app_role = "player"
        )
    

if __name__ == '__main__':
    app = GymPlayer()
    app.run(sys.argv[1:])