
# PROBER IDS
PROBER_IPERF = 1
PROBER_PING = 2
PROBER_SIPP = 3
PROBER_IPERF3 = 4
PROBER_PKTGEN = 5
PROBER_TCPREPLAY = 6

#Monitor IDs
LISTENER_HOST = 10
LISTENER_DOCKER = 11
LISTENER_PROCESS = 12
LISTENER_DNS = 13
LISTENER_SURICATA = 14