#!/usr/bin/env python3.6
# coding=utf-8

import sys

from gym.common.app import App
from gym.monitor.monitor import Monitor


class GymMonitor(App):
    def __init__(self):
        App.__init__(self)
    
    def run(self, argv):
        ack = self.cfg.parse(argv)
        if ack:
            info = self.cfg.get()
            info["role"] = "monitor"
            app_cls = Monitor
            self.init(app_cls)
        else:
            print(f'Could not start {self.__class__.__name__}')
            return -1


if __name__ == '__main__':
    app = GymMonitor()
    app.run(sys.argv[1:])