#!/usr/bin/env python3.7
# coding=utf-8

import sys

from gym.common.app import App
from gym.monitor.monitor import Monitor


class GymMonitor(App):
    def __init__(self):
        App.__init__(self,
            app_cls = Monitor,
            app_role = "monitor"
        )
            

if __name__ == '__main__':
    app = GymMonitor()
    app.run(sys.argv[1:])