#!/usr/bin/env python3.7
# coding=utf-8

import sys

from gym.common.app import App
from gym.infra.infra import Infra


class GymInfra(App):
    def __init__(self):
        App.__init__(self)
    
    def run(self, argv):
        ack = self.cfg.parse(argv)
        if ack:
            info = self.cfg.get()
            info["role"] = "infra"
            app_cls = Infra
            self.init(app_cls)
        else:
            print(f'Could not start {self.__class__.__name__}')
            return -1


if __name__ == '__main__':
    app = GymInfra()
    app.run(sys.argv[1:])
