#!/usr/bin/env python3.7
# coding=utf-8

import sys

from gym.common.app import App
from gym.infra.infra import Infra


class GymInfra(App):
    def __init__(self):
        App.__init__(self,
            app_cls = Infra,
            app_role = "infra"
        )


if __name__ == '__main__':
    app = GymInfra()
    app.run(sys.argv[1:])
