#!/usr/bin/env python3.7
# coding=utf-8

import sys

from gym.common.app import App
from gym.agent.agent import Agent


class GymAgent(App):
    def __init__(self):
        App.__init__(self,
            app_cls = Agent,
            app_role = "agent"
        )


if __name__ == '__main__':
    app = GymAgent()
    app.run(sys.argv[1:])