#!/usr/bin/env python3.8
# coding=utf-8

import sys

from gym.common.app import App
from gym.manager.manager import Manager


class GymManager(App):
    def __init__(self):
        App.__init__(self, app_cls=Manager, app_role="manager")


if __name__ == "__main__":
    app = GymManager()
    app.run(sys.argv[1:])
